//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjcompAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    
    public partial class Cart
    {
        [DataMember]
        public int CartID { get; set; }
        [DataMember]
        public Nullable<int> ProductID { get; set; }
        [DataMember]
        public double TotalPrice { get; set; }
        [DataMember]
        public int Quantity { get; set; }
        [DataMember]
        public Nullable<int> UserID { get; set; }
    }
}
