  //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjcompAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    

   
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Images = new HashSet<Image>();
        }
        [DataMember]
    
        public int ProductID { get; set; }
        [DataMember]

        public string ProductCode { get; set; }
        [DataMember]

        public string ProductName { get; set; }
        [DataMember]

        public string ProductDescription { get; set; }
        [DataMember]

        public string Brand { get; set; }
        [DataMember]

        public int Quantity { get; set; }
        [DataMember]

        public float ProductPrice { get; set; }
        [DataMember]

        public bool InStock { get; set; }
        [DataMember]

        public Nullable<int> CategoryID { get; set; }
        [DataMember]

        public System.DateTime CreatedDate { get; set; }
        [DataMember]

        public Nullable<int> ModifiedBy { get; set; }
        [DataMember]

        public Nullable<System.DateTime> ModifiedDate { get; set; }
        


        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
